package com.stocksense.service;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JwtServiceTest {

    @Test
    void testJwtTokenGenerationWithShortSecret() {
        // Test with a short 8-character secret key generated by cloud host
        JwtService jwtService = new JwtService("shortKey", 86400000L);
        String token = jwtService.generateToken("admin", "ADMIN");

        assertNotNull(token);
        assertEquals("admin", jwtService.extractUsername(token));
        assertEquals("ADMIN", jwtService.extractRole(token));
        assertTrue(jwtService.isTokenValid(token, "admin"));
    }

    @Test
    void testJwtTokenGenerationWithLongSecret() {
        JwtService jwtService = new JwtService("a-very-long-secret-key-that-is-more-than-32-characters-long-stocksense", 86400000L);
        String token = jwtService.generateToken("user1", "USER");

        assertNotNull(token);
        assertEquals("user1", jwtService.extractUsername(token));
        assertEquals("USER", jwtService.extractRole(token));
        assertTrue(jwtService.isTokenValid(token, "user1"));
    }
}
